spring:

  redis:
    host: localhost
    port: 6379
    password: admin

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    isPubSubDomain: true
