version: '2'
services:
  artemis:
    image: vromero/activemq-artemis:latest
    environment:
      ARTEMIS_USERNAME: "admin"
      ARTEMIS_PASSWORD: "admin"
    ports:
      - "8161:8161"
      - "61616:61616"
  redis:
    image: redis:5.0.5
    container_name: redis
    restart: unless-stopped
    hostname: redis
    network_mode: bridge
    ports:
      - "6379:6379/tcp"